# Generated by Django 4.2.1 on 2023-05-27 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transactionID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
